### ISSUE TITLE
Error mkdir

### ISSUE THREAD

**Issue by JuanDeDironne** [humy2833/easy-ftp#1]
Hello

When i use easy-ftp i have on error, just with the code below 
var easyFtp = require('easy-ftp');

A part of error
Error: UNKNOWN: unknown error, mkdir 'd:\test\새 폴더\test'
at Error (native)
at Object.fs.mkdirSync (fs.js:794:18)
at Object.mkdirsSync (c:\Users\xxxxx\Documents\xxxxx\node_modules\easy-ftp\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:29:9)

This seems to be linked to path.resolve()...? It's just an idea, i begin with Node JS (i have discovered   last week).

**Comment by humy2833** [comment]
oops, thank you~.
in addition, I do not speak English well.
I had the help of Google Translate program. 
The cause of the error was a test code is inserted.
The error has been corrected now , thanks .
I'm sorry, please accept again the latest version.
