### ISSUE TITLE
Multiple files upload crash

### ISSUE THREAD

**Issue by kolykhalov** [humy2833/easy-ftp#12]
Hello there!

I upload several files via separate post requests via multiple form file. I use express-fileupload. When I send I file at a time at pause 1 sec. - no problem easy-ftp sends file to server. But when I send 2+ requests with little to no pause then no upload is done and app halts. So if I wait for ftp callback - then no problem, but when in pending state the ftp client halts everything. So if I want to send 100 files simultaneously then ftp halts.

What may be a problem here?

**Comment by kolykhalov** [comment]
Maybe the problem is in IIS on Windows Server. Maybe it limits connections and easy-ftp creates separate connection per file. Is there a way to create connection pool like in tedious?

**Comment by humy2833** [comment]
You should be able to find out how you implemented it.
Can I show source code?

**Comment by kolykhalov** [comment]
I investigated deeper into this problem and found out that ftp is the main reason for this behavior.

So the plan is:

1. http://plugins.krajee.com/file-input - this library pushes async multiple files simultaneously one by one to nodejs (one file per post request).

2. This is what router does:

```
// upload images
uploadBanners: async function(req){

            var banner = req.files.banners_upload
            var ui = uuid()
            var filename = ui+path.extname(banner.name)
            var campaignId = req.params.id


            //get image size
            var dimensions = sizeOf(banner.data);

            //load image to disk then to ftp
            fs.writeFileSync('./uploads/'+filename, banner.data)

              // load file from disk to ftp
              if (await fs.exists('./uploads/'+filename))
              {
                  // delete file on upload
                  if(await upload()){
                      fs.unlinkSync('./uploads/'+filename)
                  }
              }

            // промис функция загрузки по фтп
            function upload(){
                ftp.connect(config)
                return new Promise(resolve =>
                    ftp.upload('./uploads/'+filename, "/articles", function(){
                        resolve(true)
                        console.log('done')
                        ftp.close()
                    }))
            }
```

So if I upload files one by one by hand (by pushing 'upload' button), make pauses between each one of them - then no problem, they upload. Else everything just stucks on ftp piece of code.

**Comment by humy2833** [comment]
This problem can not be resolved unless the FTP module internally supports Queue.
If you use another FTP module and you do not have a Queue system, you'll get the same result.
This is because IIS limits the connection to one.
I think you need to develop a Queue system so that you can deal with one connection directly.

**Comment by kolykhalov** [comment]
Thanks mate, best wishes! 👍
