### ISSUE TITLE
How to Use Interactive Keyboard with Easy SFTP

### ISSUE THREAD

**Issue by benjaminray3** [humy2833/easy-ftp#2]
I am attempting to connect to an SFTP server and it seems it requires Keyboard Based Authentication .

Below is my code:

---

var EasyFTP = require('easy-ftp');
var ftp = new EasyFTP();
var sleep = require('sleep-async')();
var newFile;

var config = {
    host: 'host',
    port: port,
    username: 'un',
    password: 'pw',
    type: 'sftp',
    tryKeyboard: true
};

ftp.connect(config);

ftp.on('keyboard-interactive', function(name, instructions, lang, prompts, finish) { 
console.log('Connection :: keyboard-interactive');
  finish(['my_password_on_remote_machine']);
}) 

---

**Comment by humy2833** [comment]
Unfortunately, that feature is not supported.
Sorry...
