### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by HorkyJakub** [humy2833/easy-ftp#5]
I cant connect to sftp server

```
var ftp = new easyftp();
ftp.connect({
    host:'barca.ufa.cas.cz',
    type:'sftp',
    port:22,
    username:***,
    password:***,
});
```

with this error:

> Error: All configured authentication methods failed
>     at tryNextAuth (/home/jakub/Scripts/pvmaster/node_modules/ssh2/lib/client.js:376:17)
>     at SSH2Stream.onUSERAUTH_FAILURE (/home/jakub/Scripts/pvmaster/node_modules/ssh2/lib/client.js:587:5)
>     at emitTwo (events.js:87:13)
>     at SSH2Stream.emit (events.js:172:7)
>     at parsePacket (/home/jakub/Scripts/pvmaster/node_modules/ssh2-streams/lib/ssh.js:3923:10)
>     at SSH2Stream._transform (/home/jakub/Scripts/pvmaster/node_modules/ssh2-streams/lib/ssh.js:667:13)
>     at SSH2Stream.Transform._read (_stream_transform.js:167:10)
>     at SSH2Stream._read (/home/jakub/Scripts/pvmaster/node_modules/ssh2-streams/lib/ssh.js:251:15)
>     at SSH2Stream.Transform._write (_stream_transform.js:155:12)
>     at doWrite (_stream_writable.js:292:12)

But I can connect to sftp server via winSCP with no problems.
 Could you please give me some advice?

**Comment by humy2833** [comment]
Please see below.
https://github.com/mscdex/ssh2/issues/270

**Comment by HorkyJakub** [comment]
Thanks, `keyboard-interactive` is the problem
